import Link from "next/link";
import { CampaignCard } from "@/components/campaign-card";
import { campaigns } from "@/components/campaign-data";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";

export default function Home() {
  return <><SiteHeader /><main><section className="hero"><div><p className="kicker">A place for practical care</p><h1>People helping people move forward.</h1><p className="lede">Raise money for the people, causes and communities that matter. Every campaign has a clear story, a visible goal and room for a whole community to show up.</p><div className="hero-actions"><Link className="button" href="/start">Start a fundraiser</Link><Link className="text-link" href="/discover">Discover fundraisers</Link></div></div><aside className="hero-note"><span className="note-mark">✦</span><p>Give with clarity.</p><small>Benefitly keeps donation, optional platform support and payment fees clearly separated before you give.</small></aside></section><section className="section"><div className="section-title"><div><p className="kicker">Campaigns in motion</p><h2>Community care, made visible</h2></div><Link className="text-link" href="/discover">See all fundraisers</Link></div><div className="campaign-grid">{campaigns.map((campaign) => <CampaignCard key={campaign.id} campaign={campaign} />)}</div></section><section id="how-it-works" className="how"><p className="kicker">How it works</p><div className="steps"><article><strong>Tell your story</strong><p>Set a goal, add context and invite people in.</p></article><article><strong>Share it simply</strong><p>Bring friends, family and your wider community together.</p></article><article><strong>Keep everyone close</strong><p>Post updates, thank supporters and manage funds responsibly.</p></article></div></section></main><SiteFooter /></>;
}
